
pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo "Build Docker Image"

                dir('week7') {
                    sh "docker build -t mypythonflaskapp ."
                }
            }
        }

        stage('Run') {
            steps {
                echo "Run application in Docker Container"

                dir('week7') {
                    sh "docker rm -f mycontainer || true"
                    sh "docker run -d -p 5001:5001 --name mycontainer mypythonflaskapp"
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}